name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag do cenário (ex: @regressivo, @smoke)'
        required: false
        default: ''
      browser:
        description: 'Browser (chrome|electron|firefox)'
        required: false
        default: 'chrome'
  schedule:
    - cron: '0 11 * * 1-5'
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      CYPRESS_TAG: ${{ github.event.inputs.tag }}
      CYPRESS_BROWSER: ${{ github.event.inputs.browser }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Run Cypress tests
        run: |
          if [ -n "${{ env.CYPRESS_TAG }}" ]; then
            npx cypress run --browser ${{ env.CYPRESS_BROWSER }} --env grepTags="${{ env.CYPRESS_TAG }}"
          else
            npx cypress run --browser ${{ env.CYPRESS_BROWSER }}
          fi

      - name: Generate Allure Report
        if: always()
        run: |
          npx allure generate allure-results --clean -o allure-report

      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-report

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4