name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag do cenário (ex: @regressivo)'
        required: false
        default: ''
      browser:
        description: 'Browser (chrome|electron|firefox)'
        required: false
        default: 'chrome'
  schedule:
    - cron: '0 11 * * 1-5'
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      CYPRESS_TAG: ${{ github.event.inputs.tag }}
      CYPRESS_BROWSER: ${{ github.event.inputs.browser }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: |
          npx cypress run --browser ${{ env.CYPRESS_BROWSER }} $([ -n "${{ env.CYPRESS_TAG }}" ] && echo "--env grepTags=${{ env.CYPRESS_TAG }}")

      - name: Generate HTML report
        run: |
          npx mochawesome-merge cypress/results/*.json > mochawesome.json
          npx marge mochawesome.json -f report -o ./cypress/results

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./cypress/results

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4