name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag do cenário (ex: @regressivo, @smoke)'
        required: false
        default: ''
      browser:
        description: 'Browser (chrome|electron|firefox)'
        required: false
        default: 'chrome'
  schedule:
    - cron: '0 11 * * 1-5'
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      CYPRESS_TAG: ${{ github.event.inputs.tag }}
      CYPRESS_BROWSER: ${{ github.event.inputs.browser }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: |
          if [ -n "${{ env.CYPRESS_TAG }}" ]; then
            npx cypress run --browser ${{ env.CYPRESS_BROWSER }} --env grepTags="${{ env.CYPRESS_TAG }}"
          else
            npx cypress run --browser ${{ env.CYPRESS_BROWSER }}
          fi

      - name: Debug - List allure-results contents
        if: always()
        run: |
          echo "Checking allure-results directory..."
          ls -la allure-results/ || echo "allure-results directory not found"
          echo "Contents of allure-results:"
          find allure-results -type f -name "*.json" | head -10 || echo "No JSON files found"

      - name: Generate Allure Report
        if: always()
        run: |
          if [ -d "allure-results" ] && [ "$(ls -A allure-results)" ]; then
            npx allure generate allure-results --clean -o allure-report
            echo "Allure report generated successfully"
            ls -la allure-report/
          else
            echo "No allure-results found, creating empty report"
            mkdir -p allure-report
            echo "<h1>No test results found</h1>" > allure-report/index.html
          fi

      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-report

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4